/* eslint-disable react/function-component-definition */
import './globals.css';
import { Source_Sans_Pro } from '@next/font/google';
import RootStyleRegistry from './emotion';

const SOURCE_SANS_PRO = Source_Sans_Pro({
  subsets: ['latin'],
  weight: ['200', '300', '400', '600', '700', '900'],
  style: ['normal', 'italic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang='en'>
      <body className={`${SOURCE_SANS_PRO.className}`}>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
